#ifndef _COMMANDS_LIST_H_
#define _COMMANDS_LIST_H_


/* DEFINITIONS OF RECIEVEABLE COMMANDS */

#define GET_STATUS_COMMAND				0xAA
#define ENABLE_SYSTEM_COMMAND			0xEE
#define DISABLE_SYSTEM_COMMAND			0xDD

#define GET_MOISTURE_READING_COMMAND	0xBB
#define GET_TEMP_READING_COMMAND		0xCC 

#endif
